// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUI_Calculator.SharedClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class Shared
    {
        
        /// <summary>
        /// SwitchToBasic - Use 'SwitchToBasicParams' to pass parameters into this method.
        /// </summary>
        public void SwitchToBasic()
        {
            #region Variable Declarations
            WinTitleBar uICalculatorTitleBar = this.UICalculatorWindow.UICalculatorTitleBar;
            WinText uIItem0Text = this.UICalculatorWindow.UIItem0Window.UIItem0Text;
            #endregion

            // Click 'Calculator' title bar
            Mouse.Click(uICalculatorTitleBar, new Point(36, 9));

            // Type 'Alt + 1' in '0' label
            Keyboard.SendKeys(uIItem0Text, this.SwitchToBasicParams.UIItem0TextSendKeys, ModifierKeys.Alt);
        }
        
        /// <summary>
        /// SwitchToScien - Use 'SwitchToScienParams' to pass parameters into this method.
        /// </summary>
        public void SwitchToScien()
        {
            #region Variable Declarations
            WinTitleBar uICalculatorTitleBar = this.UICalculatorWindow.UICalculatorTitleBar;
            WinText uIItem0Text = this.UICalculatorWindow.UIItem0Window.UIItem0Text;
            #endregion

            // Click 'Calculator' title bar
            Mouse.Click(uICalculatorTitleBar, new Point(54, 7));

            // Type 'Alt + 2' in '0' label
            Keyboard.SendKeys(uIItem0Text, this.SwitchToScienParams.UIItem0TextSendKeys, ModifierKeys.Alt);
        }
        
        /// <summary>
        /// SwitchToProgrammer - Use 'SwitchToProgrammerParams' to pass parameters into this method.
        /// </summary>
        public void SwitchToProgrammer()
        {
            #region Variable Declarations
            WinText uIItem0Text = this.UICalculatorWindow.UIItem0Window.UIItem0Text;
            WinTitleBar uICalculatorTitleBar = this.UICalculatorWindow.UICalculatorTitleBar;
            #endregion

            // Last mouse action was not recorded.

            // Type 'Alt + 3' in '0' label
            Keyboard.SendKeys(uIItem0Text, this.SwitchToProgrammerParams.UIItem0TextSendKeys, ModifierKeys.Alt);

            // Click 'Calculator' title bar while pressing Alt
            Mouse.Click(uICalculatorTitleBar, MouseButtons.Left, ModifierKeys.Alt, new Point(149, 10));
        }
        
        /// <summary>
        /// SwitchToStatistics - Use 'SwitchToStatisticsParams' to pass parameters into this method.
        /// </summary>
        public void SwitchToStatistics()
        {
            #region Variable Declarations
            WinTitleBar uICalculatorTitleBar = this.UICalculatorWindow.UICalculatorTitleBar;
            WinText uIItem0Text = this.UICalculatorWindow.UIItem0Window.UIItem0Text;
            #endregion

            // Click 'Calculator' title bar
            Mouse.Click(uICalculatorTitleBar, new Point(151, 14));

            // Type 'Alt + 4' in '0' label
            Keyboard.SendKeys(uIItem0Text, this.SwitchToStatisticsParams.UIItem0TextSendKeys, ModifierKeys.Alt);
        }
        
        #region Properties
        public virtual SwitchToBasicParams SwitchToBasicParams
        {
            get
            {
                if ((this.mSwitchToBasicParams == null))
                {
                    this.mSwitchToBasicParams = new SwitchToBasicParams();
                }
                return this.mSwitchToBasicParams;
            }
        }
        
        public virtual SwitchToScienParams SwitchToScienParams
        {
            get
            {
                if ((this.mSwitchToScienParams == null))
                {
                    this.mSwitchToScienParams = new SwitchToScienParams();
                }
                return this.mSwitchToScienParams;
            }
        }
        
        public virtual SwitchToProgrammerParams SwitchToProgrammerParams
        {
            get
            {
                if ((this.mSwitchToProgrammerParams == null))
                {
                    this.mSwitchToProgrammerParams = new SwitchToProgrammerParams();
                }
                return this.mSwitchToProgrammerParams;
            }
        }
        
        public virtual SwitchToStatisticsParams SwitchToStatisticsParams
        {
            get
            {
                if ((this.mSwitchToStatisticsParams == null))
                {
                    this.mSwitchToStatisticsParams = new SwitchToStatisticsParams();
                }
                return this.mSwitchToStatisticsParams;
            }
        }
        
        public UICalculatorWindow UICalculatorWindow
        {
            get
            {
                if ((this.mUICalculatorWindow == null))
                {
                    this.mUICalculatorWindow = new UICalculatorWindow();
                }
                return this.mUICalculatorWindow;
            }
        }
        #endregion
        
        #region Fields
        private SwitchToBasicParams mSwitchToBasicParams;
        
        private SwitchToScienParams mSwitchToScienParams;
        
        private SwitchToProgrammerParams mSwitchToProgrammerParams;
        
        private SwitchToStatisticsParams mSwitchToStatisticsParams;
        
        private UICalculatorWindow mUICalculatorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SwitchToBasic'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SwitchToBasicParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Alt + 1' in '0' label
        /// </summary>
        public string UIItem0TextSendKeys = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SwitchToScien'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SwitchToScienParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Alt + 2' in '0' label
        /// </summary>
        public string UIItem0TextSendKeys = "2";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SwitchToProgrammer'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SwitchToProgrammerParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Alt + 3' in '0' label
        /// </summary>
        public string UIItem0TextSendKeys = "3";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SwitchToStatistics'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SwitchToStatisticsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Alt + 4' in '0' label
        /// </summary>
        public string UIItem0TextSendKeys = "4";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICalculatorWindow : WinWindow
    {
        
        public UICalculatorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Calculator";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CalcFrame";
            this.WindowTitles.Add("Calculator");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UICalculatorTitleBar
        {
            get
            {
                if ((this.mUICalculatorTitleBar == null))
                {
                    this.mUICalculatorTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUICalculatorTitleBar.WindowTitles.Add("Calculator");
                    #endregion
                }
                return this.mUICalculatorTitleBar;
            }
        }
        
        public UIItem0Window UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new UIItem0Window(this);
                }
                return this.mUIItem0Window;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUICalculatorTitleBar;
        
        private UIItem0Window mUIItem0Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItem0Window : WinWindow
    {
        
        public UIItem0Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "150";
            this.WindowTitles.Add("Calculator");
            #endregion
        }
        
        #region Properties
        public WinText UIItem0Text
        {
            get
            {
                if ((this.mUIItem0Text == null))
                {
                    this.mUIItem0Text = new WinText(this);
                    #region Search Criteria
                    this.mUIItem0Text.SearchProperties[WinText.PropertyNames.Name] = "Result";
                    this.mUIItem0Text.WindowTitles.Add("Calculator");
                    #endregion
                }
                return this.mUIItem0Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIItem0Text;
        #endregion
    }
}
